import type { Place, Region } from './types'

/**
 * 장소 카탈로그 시드 데이터.
 * 데모 모드에서는 이 배열이 그대로 카탈로그가 되고,
 * Supabase 연결 시에는 supabase/seed.sql 이 동일한 데이터를 places 테이블에 적재한다.
 */
export const SEED_PLACES: Place[] = [
  // ── 서울 성수 ─────────────────────────────────────────────
  {
    id: 'p-seongsu-01',
    name: '성수동 소금집 델리',
    category: 'babzip',
    region: '서울 성수',
    address: '서울 성동구 연무장길 33',
    lat: 37.5445,
    lng: 127.0557,
    image_url: null,
    rating: 4.6,
    price_level: 3,
    tags: ['로컬맛집', '가성비'],
    summary: '직접 염장한 샤퀴테리 플래터로 유명한 성수 대표 델리.',
    open_hours: '11:30 - 21:00',
    waiting_count: 12,
  },
  {
    id: 'p-seongsu-02',
    name: '대림창고 갤러리 카페',
    category: 'cafe',
    region: '서울 성수',
    address: '서울 성동구 성수이로 78',
    lat: 37.5423,
    lng: 127.0561,
    image_url: null,
    rating: 4.3,
    price_level: 2,
    tags: ['뷰맛집', '디저트'],
    summary: '옛 정미소를 개조한 대형 창고형 카페. 비 오는 날 분위기 최고.',
    open_hours: '11:00 - 23:00',
    waiting_count: 4,
  },
  {
    id: 'p-seongsu-03',
    name: '어반소스 루프탑',
    category: 'sulzip',
    region: '서울 성수',
    address: '서울 성동구 아차산로 104',
    lat: 37.5471,
    lng: 127.0668,
    image_url: null,
    rating: 4.4,
    price_level: 3,
    tags: ['뷰맛집', '심야영업'],
    summary: '한강 야경이 보이는 루프탑 내추럴 와인 바.',
    open_hours: '17:00 - 02:00',
    waiting_count: 7,
  },
  {
    id: 'p-seongsu-04',
    name: '서울숲',
    category: 'spot',
    region: '서울 성수',
    address: '서울 성동구 뚝섬로 273',
    lat: 37.5443,
    lng: 127.0374,
    image_url: null,
    rating: 4.7,
    price_level: 1,
    tags: ['반려견 동반', '주차가능'],
    summary: '도심 속 대형 공원. 반려견 산책로와 사슴 방사장이 있다.',
    open_hours: '상시 개방',
    waiting_count: 0,
  },
  {
    id: 'p-seongsu-05',
    name: '베지테리언 성수',
    category: 'babzip',
    region: '서울 성수',
    address: '서울 성동구 서울숲2길 19',
    lat: 37.5462,
    lng: 127.0442,
    image_url: null,
    rating: 4.5,
    price_level: 2,
    tags: ['비건', '혼밥'],
    summary: '제철 채소로만 구성한 비건 정식 단일 메뉴.',
    open_hours: '11:00 - 20:00',
    waiting_count: 9,
  },
  {
    id: 'p-seongsu-06',
    name: '언더스탠드에비뉴',
    category: 'spot',
    region: '서울 성수',
    address: '서울 성동구 왕십리로 63',
    lat: 37.5449,
    lng: 127.0424,
    image_url: null,
    rating: 4.1,
    price_level: 1,
    tags: ['로컬맛집', '반려견 동반'],
    summary: '컨테이너 편집숍 거리. 서울숲과 이어져 산책 코스로 좋다.',
    open_hours: '11:00 - 21:00',
    waiting_count: 0,
  },

  // ── 제주 ────────────────────────────────────────────────
  {
    id: 'p-jeju-01',
    name: '올레국수 본점',
    category: 'babzip',
    region: '제주',
    address: '제주시 귀아랑길 24',
    lat: 33.4996,
    lng: 126.5312,
    image_url: null,
    rating: 4.5,
    price_level: 2,
    tags: ['노포', '가성비'],
    summary: '제주 고기국수의 기준. 오픈런 필수.',
    open_hours: '09:00 - 20:00',
    waiting_count: 21,
  },
  {
    id: 'p-jeju-02',
    name: '카페 델문도',
    category: 'cafe',
    region: '제주',
    address: '제주시 조천읍 조함해안로 519-10',
    lat: 33.5432,
    lng: 126.6698,
    image_url: null,
    rating: 4.4,
    price_level: 2,
    tags: ['뷰맛집', '디저트'],
    summary: '함덕 해변 바로 앞 오션뷰 로스터리 카페.',
    open_hours: '07:00 - 22:00',
    waiting_count: 6,
  },
  {
    id: 'p-jeju-03',
    name: '성산일출봉',
    category: 'spot',
    region: '제주',
    address: '서귀포시 성산읍 일출로 284-12',
    lat: 33.4581,
    lng: 126.9425,
    image_url: null,
    rating: 4.8,
    price_level: 1,
    tags: ['뷰맛집', '주차가능'],
    summary: '유네스코 세계자연유산. 일출 시각 기준 1시간 전 도착 권장.',
    open_hours: '07:00 - 20:00',
    waiting_count: 0,
  },
  {
    id: 'p-jeju-04',
    name: '흑돼지 거리 돈사돈',
    category: 'babzip',
    region: '제주',
    address: '제주시 원노형로 88',
    lat: 33.4738,
    lng: 126.4805,
    image_url: null,
    rating: 4.6,
    price_level: 4,
    tags: ['로컬맛집', '주차가능'],
    summary: '두툼한 근고기를 멜젓에 찍어 먹는 제주 흑돼지 성지.',
    open_hours: '12:00 - 22:00',
    waiting_count: 18,
  },
  {
    id: 'p-jeju-05',
    name: '월정리 해변 펍',
    category: 'sulzip',
    region: '제주',
    address: '제주시 구좌읍 월정1길 29',
    lat: 33.5563,
    lng: 126.7955,
    image_url: null,
    rating: 4.2,
    price_level: 3,
    tags: ['뷰맛집', '심야영업'],
    summary: '에메랄드빛 월정리 바다를 보며 마시는 수제 맥주.',
    open_hours: '16:00 - 01:00',
    waiting_count: 3,
  },
  {
    id: 'p-jeju-06',
    name: '비건 하우스 제주',
    category: 'babzip',
    region: '제주',
    address: '서귀포시 안덕면 산방로 141',
    lat: 33.2394,
    lng: 126.3155,
    image_url: null,
    rating: 4.3,
    price_level: 2,
    tags: ['비건', '반려견 동반'],
    summary: '제주 채소로 만든 비건 커리와 통곡물 볼. 반려견 동반 가능.',
    open_hours: '10:30 - 19:00',
    waiting_count: 5,
  },
  {
    id: 'p-jeju-07',
    name: 'camellia hill 동백수목원',
    category: 'spot',
    region: '제주',
    address: '서귀포시 안덕면 병악로 166',
    lat: 33.2892,
    lng: 126.3653,
    image_url: null,
    rating: 4.5,
    price_level: 2,
    tags: ['반려견 동반', '주차가능'],
    summary: '6,000그루 동백 수목원. 겨울철 개화 시즌이 절정.',
    open_hours: '08:30 - 18:00',
    waiting_count: 0,
  },

  // ── 부산 ────────────────────────────────────────────────
  {
    id: 'p-busan-01',
    name: '해운대 암소갈비집',
    category: 'babzip',
    region: '부산',
    address: '부산 해운대구 중동2로10번길 32-10',
    lat: 35.1626,
    lng: 129.1618,
    image_url: null,
    rating: 4.7,
    price_level: 4,
    tags: ['노포', '주차가능'],
    summary: '1964년 개업. 부산 3대 갈비로 꼽히는 노포.',
    open_hours: '11:00 - 22:00',
    waiting_count: 24,
  },
  {
    id: 'p-busan-02',
    name: '흰여울문화마을 카페',
    category: 'cafe',
    region: '부산',
    address: '부산 영도구 흰여울길 307',
    lat: 35.0785,
    lng: 129.0442,
    image_url: null,
    rating: 4.4,
    price_level: 2,
    tags: ['뷰맛집', '디저트'],
    summary: '절벽 위 골목 카페. 남항 바다가 통창으로 들어온다.',
    open_hours: '10:00 - 20:00',
    waiting_count: 8,
  },
  {
    id: 'p-busan-03',
    name: '감천문화마을',
    category: 'spot',
    region: '부산',
    address: '부산 사하구 감내2로 203',
    lat: 35.0975,
    lng: 129.011,
    image_url: null,
    rating: 4.5,
    price_level: 1,
    tags: ['뷰맛집', '로컬맛집'],
    summary: '알록달록 계단식 마을. 도보 이동이 많아 편한 신발 권장.',
    open_hours: '09:00 - 18:00',
    waiting_count: 0,
  },
  {
    id: 'p-busan-04',
    name: '전포 카페거리 모모스',
    category: 'cafe',
    region: '부산',
    address: '부산 부산진구 전포대로209번길 7',
    lat: 35.1546,
    lng: 129.0633,
    image_url: null,
    rating: 4.6,
    price_level: 2,
    tags: ['디저트', '혼밥'],
    summary: '월드 바리스타 챔피언의 로스터리. 핸드드립 라인업이 넓다.',
    open_hours: '09:00 - 21:00',
    waiting_count: 11,
  },
  {
    id: 'p-busan-05',
    name: '광안리 포차거리',
    category: 'sulzip',
    region: '부산',
    address: '부산 수영구 광안해변로 219',
    lat: 35.1533,
    lng: 129.1187,
    image_url: null,
    rating: 4.3,
    price_level: 3,
    tags: ['심야영업', '뷰맛집'],
    summary: '광안대교 야경을 배경으로 한 해변 포차 라인.',
    open_hours: '18:00 - 03:00',
    waiting_count: 14,
  },
  {
    id: 'p-busan-06',
    name: '자갈치 시장 회센터',
    category: 'babzip',
    region: '부산',
    address: '부산 중구 자갈치해안로 52',
    lat: 35.0966,
    lng: 129.0304,
    image_url: null,
    rating: 4.2,
    price_level: 3,
    tags: ['노포', '로컬맛집'],
    summary: '즉석에서 뜬 활어회를 2층에서 상차림으로. 현금 결제 우대.',
    open_hours: '08:00 - 22:00',
    waiting_count: 6,
  },

  // ── 경주 ────────────────────────────────────────────────
  {
    id: 'p-gyeongju-01',
    name: '황리단길 밀면집',
    category: 'babzip',
    region: '경주',
    address: '경북 경주시 포석로 1076',
    lat: 35.8377,
    lng: 129.2119,
    image_url: null,
    rating: 4.4,
    price_level: 2,
    tags: ['가성비', '혼밥'],
    summary: '황리단길 초입의 밀면 노포. 회전이 빨라 대기가 짧다.',
    open_hours: '10:30 - 20:30',
    waiting_count: 9,
  },
  {
    id: 'p-gyeongju-02',
    name: '첨성대',
    category: 'spot',
    region: '경주',
    address: '경북 경주시 인왕동 839-1',
    lat: 35.8348,
    lng: 129.219,
    image_url: null,
    rating: 4.5,
    price_level: 1,
    tags: ['주차가능', '뷰맛집'],
    summary: '동양 최고(最古) 천문대. 야간 조명 시간대가 특히 좋다.',
    open_hours: '상시 개방',
    waiting_count: 0,
  },
  {
    id: 'p-gyeongju-03',
    name: '경주 한옥카페 오후',
    category: 'cafe',
    region: '경주',
    address: '경북 경주시 첨성로 77',
    lat: 35.8395,
    lng: 129.2126,
    image_url: null,
    rating: 4.5,
    price_level: 2,
    tags: ['디저트', '반려견 동반'],
    summary: '기와 마당을 낀 한옥 카페. 마당석엔 반려견 동반 가능.',
    open_hours: '10:00 - 21:00',
    waiting_count: 7,
  },
  {
    id: 'p-gyeongju-04',
    name: '동궁과 월지',
    category: 'spot',
    region: '경주',
    address: '경북 경주시 원화로 102',
    lat: 35.8348,
    lng: 129.2262,
    image_url: null,
    rating: 4.8,
    price_level: 2,
    tags: ['뷰맛집', '주차가능'],
    summary: '야경 명소. 일몰 30분 후 반영 사진이 가장 잘 나온다.',
    open_hours: '09:00 - 22:00',
    waiting_count: 0,
  },
  {
    id: 'p-gyeongju-05',
    name: '황남동 막걸리집',
    category: 'sulzip',
    region: '경주',
    address: '경북 경주시 황남동 155-3',
    lat: 35.8362,
    lng: 129.2148,
    image_url: null,
    rating: 4.2,
    price_level: 2,
    tags: ['노포', '가성비'],
    summary: '경주 법주와 파전을 내는 오래된 골목집.',
    open_hours: '16:00 - 24:00',
    waiting_count: 5,
  },
  {
    id: 'p-gyeongju-06',
    name: '불국사',
    category: 'spot',
    region: '경주',
    address: '경북 경주시 불국로 385',
    lat: 35.7898,
    lng: 129.332,
    image_url: null,
    rating: 4.7,
    price_level: 2,
    tags: ['주차가능', '로컬맛집'],
    summary: '유네스코 세계문화유산. 관람에 최소 1시간 30분 필요.',
    open_hours: '07:00 - 18:00',
    waiting_count: 0,
  },
]

/**
 * 데모 모드(백엔드 미연결)에서 쓰는 지역 목록.
 * Supabase 연결 시에는 regions 테이블의 값을 대신 쓴다 — 이 배열과 정확히
 * 같은 이름·좌표·순서로 시드되어 있으므로(supabase/seed.sql), 두 모드의
 * 동작이 일치한다.
 */
export const DEMO_REGIONS: Region[] = [
  { name: '서울 성수', lat: 37.5449, lng: 127.0504, sort_order: 0 },
  { name: '제주', lat: 33.4257, lng: 126.5857, sort_order: 1 },
  { name: '부산', lat: 35.1239, lng: 129.0716, sort_order: 2 },
  { name: '경주', lat: 35.8288, lng: 129.2361, sort_order: 3 },
]
